# Generated by Django 3.0.2 on 2020-02-21 16:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '0029_auto_20200221_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('points', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('correct', models.BooleanField(default=None, null=True)),
                ('comment', models.TextField(blank=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Page')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Layer')),
            ],
            options={
                'unique_together': {('floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MarkerVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=32)),
                ('value', models.TextField()),
                ('wrong', models.BooleanField(default=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoplan.Marker')),
            ],
            options={
                'unique_together': {('marker', 'key')},
            },
        ),
    ]
