# Generated by Django 3.0.2 on 2021-01-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoplan', '0005_auto_20201228_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='comment',
        ),
        migrations.CreateModel(
            name='MarkerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoplan.Marker')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
