# Generated by Django 3.0.2 on 2021-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplan', '0007_markervariable_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markervariable',
            name='key',
            field=models.IntegerField(editable=False),
        ),
    ]
