# Generated by Django 3.0.2 on 2021-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplan', '0009_auto_20210126_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
