# Generated by Django 3.0.2 on 2021-04-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoplan', '0010_marker_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ['ordinal']},
        ),
        migrations.RemoveField(
            model_name='marker',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='points',
        ),
    ]
