# Generated by Django 3.0.2 on 2021-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplan', '0011_auto_20210413_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
