# Generated by Django 3.0.2 on 2021-12-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoplan', '0012_marker_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerFingerpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side1_enabled', models.BooleanField(default=True)),
                ('side2_enabled', models.BooleanField(default=False)),
                ('side3_enabled', models.BooleanField(default=False)),
                ('side4_enabled', models.BooleanField(default=False)),
                ('side5_enabled', models.BooleanField(default=False)),
                ('side6_enabled', models.BooleanField(default=False)),
                ('side7_enabled', models.BooleanField(default=False)),
                ('side8_enabled', models.BooleanField(default=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoplan.Marker')),
            ],
        ),
    ]
