# Generated by Django 3.0.2 on 2022-03-26 16:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0061_auto_20220326_1925'),
        ('infoplan', '0013_markerfingerpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerCaptionPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('layer_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.LayerGroup')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoplan.Marker')),
            ],
        ),
    ]
