# Generated by Django 3.0.2 on 2021-02-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='date_updated',
        ),
    ]
