# Generated by Django 3.0.2 on 2021-04-24 16:39

from django.db import migrations, models
import zoloto_viewer.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210413_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=zoloto_viewer.documents.models.additional_files_upload_path),
        ),
    ]
