# Generated by Django 3.0.2 on 2020-01-06 20:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zoloto_viewer.viewer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_caption', models.TextField(null=True)),
                ('plan', models.ImageField(default=None, null=True, upload_to=zoloto_viewer.viewer.models.plan_upload_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Project')),
            ],
            options={
                'unique_together': {('project', 'floor_caption')},
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('points', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('variables', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('checked', models.BooleanField(default=None, null=True)),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Layer')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Page')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('project', 'title')},
        ),
    ]
