# Generated by Django 3.0.2 on 2020-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='indd_floor',
            field=models.TextField(editable=False, null=True),
        ),
    ]
