# Generated by Django 3.0.2 on 2020-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_page_indd_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='page',
            new_name='floor',
        ),
        migrations.AlterField(
            model_name='page',
            name='indd_floor',
            field=models.TextField(default=' ', editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
