# Generated by Django 3.0.2 on 2020-01-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20200107_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'floor_caption')},
        ),
    ]
