# Generated by Django 3.0.2 on 2020-01-09 09:24

from os import path
from django.db import migrations, models


def csv_upload_path(obj, filename):
    return path.join(obj.project.project_files_dir(), f'layers/{filename}')


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20200107_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.AddField(
            model_name='layer',
            name='client_last_modified_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='csv_data',
            field=models.FileField(default=None, upload_to=csv_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='prev_csv_data',
            field=models.FileField(default=None, null=True, upload_to=csv_upload_path),
        ),
    ]
