# Generated by Django 3.0.2 on 2020-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20200109_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='color',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
