# Generated by Django 3.0.2 on 2020-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_page_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='plan_name',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
