# Generated by Django 3.0.2 on 2020-01-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auto_20200124_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='plan_name',
            new_name='orig_file_name',
        ),
    ]
