# Generated by Django 3.0.2 on 2020-01-27 10:30

from django.db import migrations, models
import zoloto_viewer.viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_remove_page_orig_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='next_csv_data',
            field=models.FileField(default=None, null=True, upload_to=zoloto_viewer.viewer.models.csv_upload_path),
        ),
    ]
