# Generated by Django 3.0.2 on 2020-01-27 10:44

from django.db import migrations, models
import zoloto_viewer.viewer.models


def csv_upload_next_path(obj, filename):
    return f'project_{obj.project.title}/layers/next_{filename}'


def csv_upload_prev_path(obj, filename):
    return f'project_{obj.project.title}/layers/prev_{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_layer_next_csv_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='next_csv_data',
            field=models.FileField(blank=True, default='', upload_to=csv_upload_next_path),
        ),
        migrations.AlterField(
            model_name='layer',
            name='prev_csv_data',
            field=models.FileField(blank=True, default='', upload_to=csv_upload_prev_path),
        ),
    ]
