# Generated by Django 3.0.2 on 2020-01-27 13:14

from django.db import migrations, models
import zoloto_viewer.viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20200127_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layers_info',
            field=models.FileField(blank=True, default='', upload_to=zoloto_viewer.viewer.models.additional_files_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='maps_info',
            field=models.FileField(blank=True, default='', upload_to=zoloto_viewer.viewer.models.additional_files_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='pict_codes',
            field=models.FileField(blank=True, default='', upload_to=zoloto_viewer.viewer.models.additional_files_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='poi_names',
            field=models.FileField(blank=True, default='', upload_to=zoloto_viewer.viewer.models.additional_files_upload_path),
        ),
    ]
