# Generated by Django 3.0.2 on 2020-02-02 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_auto_20200127_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layer_info_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
