# Generated by Django 3.0.2 on 2020-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_project_layer_info_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
