# Generated by Django 3.0.2 on 2020-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_auto_20200202_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
