# Generated by Django 3.0.2 on 2020-02-09 15:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_page_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='variables',
        ),
        migrations.AddField(
            model_name='marker',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='geometric_bounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='marker',
            name='number',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='MarkerVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=32)),
                ('value', models.TextField()),
                ('wrong', models.BooleanField(default=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Marker')),
            ],
            options={
                'unique_together': {('marker', 'key')},
            },
        ),
    ]
