# Generated by Django 3.0.2 on 2020-02-09 16:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_page_document_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='maps_info_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
