# Generated by Django 3.0.2 on 2020-02-14 09:18

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_project_maps_info_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('document_offset'), nulls_last=True)]},
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='next_csv_data',
            new_name='new_csv_data',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='prev_csv_data',
        ),
    ]
