# Generated by Django 3.0.2 on 2020-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_auto_20200214_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='new_csv_data',
        ),
        migrations.AddField(
            model_name='layer',
            name='sync_needed',
            field=models.BooleanField(default=False),
        ),
    ]
