# Generated by Django 3.0.2 on 2020-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_auto_20200215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
