# Generated by Django 3.0.2 on 2020-02-16 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_auto_20200215_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='id',
        ),
        migrations.AddField(
            model_name='marker',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
