# Generated by Django 3.0.2 on 2020-02-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_auto_20200216_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='checked',
            new_name='correct',
        ),
    ]
