# Generated by Django 3.0.2 on 2020-02-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_auto_20200219_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='MarkerVariable',
        ),
    ]
