# Generated by Django 3.0.2 on 2020-03-03 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_auto_20200221_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='raw_color',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
