# Generated by Django 3.0.2 on 2020-03-17 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0032_auto_20200313_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
