# Generated by Django 3.0.2 on 2020-12-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0036_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='viewer.MarkerKind'),
        ),
        migrations.AddField(
            model_name='layer',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='viewer.Color'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('project', 'title'), ('project', 'number')},
        ),
    ]
