# Generated by Django 3.0.2 on 2021-01-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0037_auto_20201212_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='geometric_bounds',
        ),
    ]
