# Generated by Django 3.0.2 on 2021-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_remove_page_geometric_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerkind',
            name='svg_figures',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
