# Generated by Django 3.0.2 on 2021-01-10 15:10

from django.db import migrations


MARKERKIND_SVG_FIGURE = {
    '1': '''
<polygon points="-3.573534936,-1.25567323 0.000001221895221,-1.25567323 -1.214195937,0.8473185897 1.214186937,0.8473185897 0.000001221895221,-1.25567323 3.573538095,-1.25567323 5.021059304,1.66402787 -5.021055907,1.66402787"/>
''',
    '2': '''
<polygon points="-3.573534936,-1.25567323 0.000001221895221,-1.25567323 -1.214195937,0.8473185897 1.214186937,0.8473185897 0.000001221895221,-1.25567323 3.573538095,-1.25567323 5.021059304,1.66402787 -5.021055907,1.66402787"/>
''',
    '3': '''
<polygon points="-3.573534936,-1.25567323 0.000001221895221,-1.25567323 -1.214195937,0.8473185897 1.214186937,0.8473185897 0.000001221895221,-1.25567323 3.573538095,-1.25567323 5.021059304,1.66402787 -5.021055907,1.66402787"/>
''',
    '4': '''
<polygon points="-3.573534936,-1.25567323 0.000001221895221,-1.25567323 -1.214195937,0.8473185897 1.214186937,0.8473185897 0.000001221895221,-1.25567323 3.573538095,-1.25567323 5.021059304,1.66402787 -5.021055907,1.66402787"/>
''',
    'угол': '''
<polygon points="-3.573534936,-1.25567323 0.000001221895221,-1.25567323 -1.214195937,0.8473185897 1.214186937,0.8473185897 0.000001221895221,-1.25567323 3.573538095,-1.25567323 5.021059304,1.66402787 -5.021055907,1.66402787"/>
''',
}


def setup_svg_mark_array(apps, schema_editor):
    MarkerKind = apps.get_model('viewer', 'MarkerKind')
    for mk in MarkerKind.objects.all():
        if mk.name in MARKERKIND_SVG_FIGURE:
            mk.svg_figures = MARKERKIND_SVG_FIGURE[mk.name]
            mk.save()


def clear_svg_mark_array(apps, schema_editor):
    MarkerKind = apps.get_model('viewer', 'MarkerKind')
    for mk in MarkerKind.objects.all():
        if mk.name in MARKERKIND_SVG_FIGURE:
            mk.svg_figures = ''
            mk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0039_markerkind_svg_figures'),
    ]

    operations = [
        migrations.RunPython(code=setup_svg_mark_array, reverse_code=clear_svg_mark_array),
    ]
