# Generated by Django 3.0.2 on 2021-01-25 08:50

from django.db import migrations, models


MARKER_KINDS_SIDES = {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 1,
}


def set_sides(apps, schema_editor):
    MarkerKind = apps.get_model('viewer', 'MarkerKind')
    for mk in MarkerKind.bucket_bounds.all():
        mk.sides = MARKER_KINDS_SIDES[mk.id] if mk.id in MARKER_KINDS_SIDES else 1
        mk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20210117_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerkind',
            name='sides',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(set_sides, migrations.RunPython.noop),
    ]
