# Generated by Django 3.0.2 on 2021-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0043_auto_20210201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='marker_size_factor',
            field=models.IntegerField(default=100),
        ),
    ]
