# Generated by Django 3.0.2 on 2021-02-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0044_page_marker_size_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['-number']},
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('project', 'title')},
        ),
    ]
