# Generated by Django 3.0.2 on 2021-02-10 12:17

import re
from django.db import migrations


def set_numbers(apps, schema_editor):
    def extract_number(title: str):
        match = re.match(r'^\d+', title)
        return int(match.group(0)) if match else None

    Layer = apps.get_model('viewer', 'Layer')
    for l in Layer.bucket_bounds.all():
        l.number = extract_number(l.title)
        l.save()


def drop_layers_numbers(apps, schema_editor):
    Layer = apps.get_model('viewer', 'Layer')
    for l in Layer.bucket_bounds.all():
        l.number = None
        l.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0045_auto_20210210_1515'),
    ]

    operations = [
        migrations.RunPython(code=set_numbers, reverse_code=drop_layers_numbers),
    ]
