# Generated by Django 3.0.2 on 2021-05-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0049_auto_20210510_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='layers_info',
        ),
        migrations.RemoveField(
            model_name='project',
            name='maps_info',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pict_codes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='poi_names',
        ),
    ]
