# Generated by Django 3.0.2 on 2021-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0050_auto_20210521_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.TextField(default=''),
        ),
    ]
