# Generated by Django 3.0.2 on 2021-10-04 12:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0052_auto_20210524_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Project')),
            ],
        ),
    ]
