# Generated by Django 3.0.2 on 2021-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0053_layergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='level',
            field=models.FloatField(null=True),
        ),
    ]
