# Generated by Django 3.0.2 on 2021-10-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0055_layergroup_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layergroup',
            options={'ordering': ['num']},
        ),
        migrations.AlterUniqueTogether(
            name='layergroup',
            unique_together={('project', 'num')},
        ),
    ]
