# Generated by Django 3.0.2 on 2021-10-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0056_auto_20211011_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['number']},
        ),
    ]
