# Generated by Django 3.0.2 on 2021-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0057_auto_20211012_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerkind',
            name='unicode_symbol',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
