# Generated by Django 3.0.2 on 2021-12-04 16:49

from django.db import migrations

MARKERKIND_UNICODE_SYMBOL = {
    'напольный': (1, '\uE905'),
    'фингерпост': (8, ' '),
}


def add_markerkinds(apps, schema_editor):
    MarkerKind = apps.get_model('viewer', 'MarkerKind')
    for name, (sides, unicode_symbol) in MARKERKIND_UNICODE_SYMBOL.items():
        MarkerKind(name=name, sides=sides, unicode_symbol=unicode_symbol).save()


def remove_markerkinds(apps, schema_editor):
    MarkerKind = apps.get_model('viewer', 'MarkerKind')
    for mk in MarkerKind.objects.all():
        if mk.name in MARKERKIND_UNICODE_SYMBOL.keys():
            mk.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0059_auto_20211204_1939'),
    ]

    operations = [
        migrations.RunPython(code=add_markerkinds, reverse_code=remove_markerkinds),
    ]
