# Generated by Django 3.0.2 on 2022-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0060_auto_20211204_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='num',
            field=models.IntegerField(default=None),
        ),
    ]
