# Generated by Django 3.0.2 on 2022-04-16 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0061_auto_20220326_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='layers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, size=None),
        ),
    ]
