# Generated by Django 3.0.2 on 2022-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0063_auto_20221029_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='level',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
