# Generated by Django 3.0.2 on 2022-10-29 14:32

from django.db import migrations


def fix_markerkind_ugol_sides(apps, schema_editor):
    MarkerKind = apps.get_model("viewer", "MarkerKind")
    marker_kink_to_update = MarkerKind.objects.filter(name='угол')
    for mk in marker_kink_to_update:
        mk.sides = 2
    MarkerKind.objects.bulk_update(marker_kink_to_update, ['sides'])


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0064_auto_20221029_1649'),
    ]

    operations = [
        migrations.RunPython(fix_markerkind_ugol_sides, migrations.RunPython.noop),
    ]
